services:
  mba-scraper:
    image: mba-scraper-dev
    platform: linux/amd64
    build:
      context: .
      args:
        - BUILD_COMMIT_SHA=localdev
    volumes:
      - ./:/code/
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - bash
      - -c
      - |
        echo "Launching aws-tools"
        sleep infinity
    restart: unless-stopped
