AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: An AWS Serverless Specification local template for testing on your machine.

Resources:
  LecturesFilterFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: src.lectures_filter.lambda_handler
      Runtime: python3.13
      CodeUri: .
      MemorySize: 128
      Tracing: Active
      Timeout: 300
      Environment:
          PYTHONPATH: "./src"

      Events:
        IncomingRequestGet:
          Type: Api
          Properties:
            Path: /
            Method: GET
